In [1]:
!pip install keras.preprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.1 MB/s eta 0:00:00


In [2]:
from tensorflow import keras
import numpy
from numpy import array
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Embedding
from keras_preprocessing.sequence import pad_sequences
#from keras.preprocessing.sequence import pad_sequences

data = """ Jack and Jill went up the hill .\n To fetch a pail of water .\n Jack fell down and broke his crown .\n And Jill came tumbling after ."""
print("Data:", data, type(data))

data_splitted=data.split('\n') #returns a list of strings
print("Data_Splitted:", data_splitted, type(data_splitted))

Data:  Jack and Jill went up the hill .
 To fetch a pail of water .
 Jack fell down and broke his crown .
 And Jill came tumbling after . <class 'str'>
Data_Splitted: [' Jack and Jill went up the hill .', ' To fetch a pail of water .', ' Jack fell down and broke his crown .', ' And Jill came tumbling after .'] <class 'list'>


In [3]:
tokenizer=Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\]^_`{|}~')
tokenizer.fit_on_texts(data_splitted) #learns a vocabulary
print("Word Indices:", tokenizer.word_index) #tokenizer.word_index is a dictionary
vocab_size = len(tokenizer.word_index) + 1
print("Vocab Size:", vocab_size)
sequences=tokenizer.texts_to_sequences(data_splitted) #list of list
l=len(sequences)
print("Sequences:",sequences, type(sequences), l)

Word Indices: {'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}
Vocab Size: 23
Sequences: [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> 4


In [4]:
X=list()
y=list()
for i in range(len(sequences)):
  X.insert(i,sequences[i][:-1])
  y.insert(i,sequences[i])
print("X=", X, "y=",y, type(X), type(y))

X= [[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]] y= [[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]] <class 'list'> <class 'list'>


In [5]:
maxlen = max([len(sequence) for sequence in X])
print("Maxlen:",maxlen)
#X=array(X)
#y=array(y)
#X=numpy.reshape(X,newshape=(l,-1))
#y=numpy.reshape(y,newshape=(l,-1))
X=pad_sequences(X,maxlen=maxlen+1,padding='pre') # +1 to have 0 as the first input
print("X:",X, type(X), X.shape)
y=pad_sequences(y,maxlen=maxlen+1,padding='pre')
print("y:",y, type(y), y.shape)
#z=numpy.
#for i in range(l):
#  z[i]=to_categorical(y[i],num_classes=vocab_size)  
#print("X=", X, "y=",y)
y=to_categorical(y,num_classes=vocab_size)
print("X=", X, "y=",y, type(X), type(y), X.shape, y.shape)
model=Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10))
print(model.output_shape)
model.add(SimpleRNN(units=50, return_sequences=True))
print(model.output_shape)
model.add(Dense(units=vocab_size,activation='softmax'))
model.summary()
print("Input Shape of all Layers:",model.layers[0].input_shape,model.layers[1].input_shape,model.layers[2].input_shape)
print("Input Dim:",model.layers[0].input_dim)

Maxlen: 7
X: [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] <class 'numpy.ndarray'> (4, 8)
y: [[ 3  2  4  5  6  7  8  1]
 [ 0  9 10 11 12 13 14  1]
 [ 3 15 16  2 17 18 19  1]
 [ 0  0  2  4 20 21 22  1]] <class 'numpy.ndarray'> (4, 8)
X= [[ 0  3  2  4  5  6  7  8]
 [ 0  0  9 10 11 12 13 14]
 [ 0  3 15 16  2 17 18 19]
 [ 0  0  0  2  4 20 21 22]] y= [[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[

In [6]:
model.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=0)

In [7]:
def prob_of_input_sentence(model, tokenizer, sentence):
  print("Input Sentence:", sentence)
  encoded=tokenizer.texts_to_sequences([sentence])[0]
  encoded.insert(0,0)
  encoded=array(encoded)
  encoded=numpy.reshape(encoded,newshape=(1,-1))
  print("Encoded:", encoded, encoded.shape)
  prob=model.predict(encoded, verbose=0)
  print("Prob:", prob, prob.shape)
  probability=1
  for i in range(prob.shape[1]-1):
    probability = probability * prob[0,i,encoded[0,i+1]]
  print("Probability of Sentence", "\"", sentence, "\"", "is:", probability)

In [8]:
print("-------------------Probability of Input Sentence------------------------------")  
prob_of_input_sentence(model, tokenizer, "Jack and Jill Went")
prob_of_input_sentence(model, tokenizer, "and Jill Went up")
prob_of_input_sentence(model, tokenizer, "went up the hill")
prob_of_input_sentence(model, tokenizer, "jack and Jill Went up the hill .")
prob_of_input_sentence(model, tokenizer, "to fetch a pail")
prob_of_input_sentence(model, tokenizer, "fetch a pail")
prob_of_input_sentence(model, tokenizer, "to fetch a pail of water")
prob_of_input_sentence(model, tokenizer, "jack fell down and")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke")
prob_of_input_sentence(model, tokenizer, "fell down and broke")
prob_of_input_sentence(model, tokenizer, "jack fell down and broke his crown")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling")
prob_of_input_sentence(model, tokenizer, "g after")
prob_of_input_sentence(model, tokenizer, "and jill came tumbling after .")
print("-------------------------------------------------------------------------------")

-------------------Probability of Input Sentence------------------------------
Input Sentence: Jack and Jill Went
Encoded: [[0 3 2 4 5]] (1, 5)
Prob: [[[4.6157274e-01 1.7771063e-03 6.2052784e-03 4.7077295e-01 4.8390237e-04
   1.4166023e-03 3.8692276e-03 1.3154852e-03 5.6492561e-04 3.0138159e-02
   1.1628408e-03 1.2796569e-03 3.0478474e-03 2.7101731e-04 6.7628094e-04
   4.0092976e-03 2.6442872e-03 1.1587354e-03 1.0461021e-03 7.9121516e-04
   8.0027233e-04 3.3595392e-03 1.6365274e-03]
  [4.5824379e-02 7.6953956e-04 4.3697664e-01 1.0503844e-03 1.8107056e-03
   7.3435614e-05 8.4851292e-04 5.4142270e-03 2.7185138e-03 6.4629667e-02
   1.8805273e-02 8.4969198e-04 5.4946160e-03 1.9397341e-03 1.4687928e-04
   4.0706569e-01 2.7772758e-04 4.4355608e-04 3.8581516e-04 1.5496192e-03
   1.8019124e-04 4.1419073e-04 2.3311297e-03]
  [6.4268163e-05 2.6811313e-04 1.5496376e-03 3.1370644e-05 8.7484175e-01
   1.1467652e-03 3.0196416e-06 2.1756449e-04 3.6738736e-03 6.5282162e-05
   1.5009072e-02 3.5208140e-

In [9]:
prob_of_input_sentence(model, tokenizer, "and jill came walkings after .")

Input Sentence: and jill came walkings after .
Encoded: [[ 0  2  4 20 22  1]] (1, 6)
Prob: [[[4.61572737e-01 1.77710631e-03 6.20527845e-03 4.70772952e-01
   4.83902375e-04 1.41660229e-03 3.86922760e-03 1.31548522e-03
   5.64925605e-04 3.01381592e-02 1.16284075e-03 1.27965689e-03
   3.04784742e-03 2.71017314e-04 6.76280935e-04 4.00929758e-03
   2.64428719e-03 1.15873537e-03 1.04610214e-03 7.91215163e-04
   8.00272333e-04 3.35953920e-03 1.63652736e-03]
  [3.04172747e-02 5.99911960e-04 4.14218277e-01 6.25415123e-04
   3.80500685e-03 1.42372330e-04 1.01207406e-03 5.30191790e-03
   3.18965060e-03 4.42566499e-02 2.46529933e-02 1.03445351e-03
   6.15310995e-03 3.31451418e-03 2.10139639e-04 4.53291267e-01
   2.45444535e-04 8.16268672e-04 5.22009970e-04 2.19241017e-03
   2.36998414e-04 4.65899997e-04 3.29592451e-03]
  [2.23070965e-04 3.12734890e-04 1.02756347e-03 2.43884147e-04
   6.03232682e-01 3.27813695e-03 1.16425417e-05 1.59738571e-04
   2.15392606e-03 1.69587031e-04 1.50372339e-02 8.78450