In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense
from tensorflow.keras.metrics import categorical_crossentropy

**OR Gate**

In [2]:
training_data=np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
target_data=np.array([[0],[1],[1],[1]],'float32')

In [3]:
model=Sequential()

In [4]:
model.add(Dense(8,input_dim=2,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [5]:
model.compile(loss='mean_squared_error',
             optimizer='adam',
             metrics=['binary_accuracy'])

In [6]:
model.summary();

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 24        
                                                                 
 dense_1 (Dense)             (None, 1)                 9         
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.fit(training_data,target_data,epochs=500,verbose=2,shuffle=True)

Epoch 1/500
1/1 - 1s - loss: 0.4042 - binary_accuracy: 0.2500 - 814ms/epoch - 814ms/step
Epoch 2/500
1/1 - 0s - loss: 0.4031 - binary_accuracy: 0.0000e+00 - 7ms/epoch - 7ms/step
Epoch 3/500
1/1 - 0s - loss: 0.4019 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 4/500
1/1 - 0s - loss: 0.4008 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 5/500
1/1 - 0s - loss: 0.3996 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 6/500
1/1 - 0s - loss: 0.3985 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 7/500
1/1 - 0s - loss: 0.3973 - binary_accuracy: 0.0000e+00 - 7ms/epoch - 7ms/step
Epoch 8/500
1/1 - 0s - loss: 0.3962 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 9/500
1/1 - 0s - loss: 0.3951 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 10/500
1/1 - 0s - loss: 0.3939 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 11/500
1/1 - 0s - loss: 0.3928 - binary_accuracy: 0.0000e+00 - 6ms/epoch - 6ms/step
Epoch 12/500
1/1 - 

In [8]:
y=model.predict((training_data).round())

1/1 [==============================] - 0s 109ms/step


In [9]:
y

array([[0.6020885],
       [0.6020885],
       [0.5870937],
       [0.6020885]], dtype=float32)

**And Gate**

In [10]:
training_data=np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
target_data=np.array([[0],[0],[0],[1]],'float32')

In [11]:
model.fit(training_data,target_data,epochs=500,verbose=2,shuffle=True)

Epoch 1/500
1/1 - 0s - loss: 0.3070 - binary_accuracy: 0.2500 - 8ms/epoch - 8ms/step
Epoch 2/500
1/1 - 0s - loss: 0.3071 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 3/500
1/1 - 0s - loss: 0.3072 - binary_accuracy: 0.2500 - 6ms/epoch - 6ms/step
Epoch 4/500
1/1 - 0s - loss: 0.3072 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 5/500
1/1 - 0s - loss: 0.3072 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 6/500
1/1 - 0s - loss: 0.3071 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 7/500
1/1 - 0s - loss: 0.3071 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 8/500
1/1 - 0s - loss: 0.3070 - binary_accuracy: 0.2500 - 6ms/epoch - 6ms/step
Epoch 9/500
1/1 - 0s - loss: 0.3069 - binary_accuracy: 0.2500 - 5ms/epoch - 5ms/step
Epoch 10/500
1/1 - 0s - loss: 0.3068 - binary_accuracy: 0.2500 - 6ms/epoch - 6ms/step
Epoch 11/500
1/1 - 0s - loss: 0.3066 - binary_accuracy: 0.2500 - 8ms/epoch - 8ms/step
Epoch 12/500
1/1 - 0s - loss: 0.3065 - binary_accuracy: 0.2500 

In [12]:
y=model.predict((training_data).round())

1/1 [==============================] - 0s 26ms/step


In [13]:
y

array([[0.46167335],
       [0.4780965 ],
       [0.30937365],
       [0.47806263]], dtype=float32)

**XOR Gate**

In [14]:
training_data=np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
target_data=np.array([[0],[1],[1],[0]],'float32')

In [15]:
model.fit(training_data,target_data,epochs=500,verbose=2,shuffle=True)

Epoch 1/500
1/1 - 0s - loss: 0.2978 - binary_accuracy: 0.5000 - 8ms/epoch - 8ms/step
Epoch 2/500
1/1 - 0s - loss: 0.2978 - binary_accuracy: 0.5000 - 8ms/epoch - 8ms/step
Epoch 3/500
1/1 - 0s - loss: 0.2978 - binary_accuracy: 0.5000 - 7ms/epoch - 7ms/step
Epoch 4/500
1/1 - 0s - loss: 0.2978 - binary_accuracy: 0.5000 - 6ms/epoch - 6ms/step
Epoch 5/500
1/1 - 0s - loss: 0.2978 - binary_accuracy: 0.5000 - 7ms/epoch - 7ms/step
Epoch 6/500
1/1 - 0s - loss: 0.2977 - binary_accuracy: 0.5000 - 7ms/epoch - 7ms/step
Epoch 7/500
1/1 - 0s - loss: 0.2976 - binary_accuracy: 0.5000 - 6ms/epoch - 6ms/step
Epoch 8/500
1/1 - 0s - loss: 0.2975 - binary_accuracy: 0.5000 - 6ms/epoch - 6ms/step
Epoch 9/500
1/1 - 0s - loss: 0.2974 - binary_accuracy: 0.5000 - 6ms/epoch - 6ms/step
Epoch 10/500
1/1 - 0s - loss: 0.2973 - binary_accuracy: 0.5000 - 6ms/epoch - 6ms/step
Epoch 11/500
1/1 - 0s - loss: 0.2971 - binary_accuracy: 0.5000 - 5ms/epoch - 5ms/step
Epoch 12/500
1/1 - 0s - loss: 0.2969 - binary_accuracy: 0.5000 

In [16]:
y=model.predict((training_data).round())

1/1 [==============================] - 0s 26ms/step


In [17]:
y

array([[0.47614324],
       [0.506965  ],
       [0.41913694],
       [0.4494345 ]], dtype=float32)